### PR TITLE
Here's an idea, pass the actual fucking destination Host, not our own hostname

### PR DESCRIPTION
**Pull request by thieman**
@eduarenas80 I think this'll prevent the problem going forward. If this looks good, I'll push 1.0.3 to PyPi. Can you test it locally and make sure it still works? If so, we can update lib and friends to use the new version.

### CODE REVIEW

**Comment by thieman** [comment]
`The Host request-header field specifies the Internet host and port number of the resource being requested...`

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by nrschultz** [comment]
forked from Chris Ricca?

**Comment by nrschultz** [comment]
dude, thats a deep chain

**Comment by thieman** [comment]
from what i can gather nobody remembers why this fork even exists, but we're using it everywhere now so whatever

**Pull request merged**
